export async function GET() {
  return Response.json([
    {
      node: "01",
      catname: "ทีวี / เครื่องเสียง",
      catnameEN: "TV & Entertainment",
      Lv: 4,
      nprod: 1566,
      mapto: "NO      ",
      HAVENEXT: true,
      base64img: null,
      slugname: "tv-and-entertainment",
      subtitle: "",
      description: "",
      descriptionEN: "",
      showcate: true,
      items: [
        {
          node: "0101",
          catname: "ทีวี",
          catnameEN: "Televisions",
          Lv: 6,
          HAVENEXT: true,
          slugname: "tv-and-entertainment/televisions",
          subtitle: "",
          description: "",
          descriptionEN: "",
          showcate: true,
          items: [
            {
              node: "010103",
              catname: "OLED TV",
              catnameEN: "OLED TV",
              Lv: 8,
              HAVENEXT: false,
              slugname: "tv-and-entertainment/televisions/oled-tv",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 1,
            },
            {
              node: "010110",
              catname: "QNED TV",
              catnameEN: "QNED TV",
              Lv: 8,
              HAVENEXT: false,
              slugname: "tv-and-entertainment/televisions/qned-tv",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 2,
            },
            {
              node: "010109",
              catname: "QLED TV",
              catnameEN: "QLED TV",
              Lv: 8,
              HAVENEXT: false,
              slugname: "tv-and-entertainment/televisions/qled-tv",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 3,
            },
            {
              node: "010112",
              catname: "NanoCell TV",
              catnameEN: "NanoCell TV",
              Lv: 8,
              HAVENEXT: false,
              slugname: "tv-and-entertainment/televisions/nanocell-tv",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 4,
            },
            {
              node: "010101",
              catname: "LED TV",
              catnameEN: "LED TV",
              Lv: 8,
              HAVENEXT: false,
              slugname: "tv-and-entertainment/televisions/led-tv",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 5,
            },
            {
              node: "010104",
              catname: "โปรเจคเตอร์ ทีวี",
              catnameEN: "Projector TV",
              Lv: 8,
              HAVENEXT: false,
              slugname: "tv-and-entertainment/televisions/projector-tv",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 8,
            },
          ],
          seq: 99,
        },
        {
          node: "0102",
          catname: "ลำโพง",
          catnameEN: "Audio And Speakers",
          Lv: 6,
          HAVENEXT: true,
          slugname: "tv-and-entertainment/speakers",
          subtitle: "",
          description: "",
          descriptionEN: "",
          showcate: true,
          items: [
            {
              node: "010201",
              catname: "ลำโพงพกพา",
              catnameEN: "Portable Speakers",
              Lv: 8,
              HAVENEXT: false,
              slugname: "tv-and-entertainment/speakers/portable-speakers",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 1,
            },
            {
              node: "010202",
              catname: "ลำโพงแยกชิ้น และ ซับวูฟเฟอร์",
              catnameEN: "Separate Speakers & Subwoofer",
              Lv: 8,
              HAVENEXT: false,
              slugname:
                "tv-and-entertainment/speakers/separate-speakers-and-subwoofer",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 3,
            },
            {
              node: "010204",
              catname: "Public Address (PA Speakers)",
              catnameEN: "Public Address (PA Speakers)",
              Lv: 8,
              HAVENEXT: false,
              slugname:
                "tv-and-entertainment/speakers/large-public-address-speakers",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 4,
            },
            {
              node: "010206",
              catname: "อุปกรณ์เสริมสำหรับลำโพง",
              catnameEN: "Speaker accessories",
              Lv: 8,
              HAVENEXT: false,
              slugname: "tv-entertainment/speakers/speaker-accessories",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 5,
            },
          ],
          seq: 99,
        },
        {
          node: "0103",
          catname: "เครื่องเสียง",
          catnameEN: "Speakers",
          Lv: 6,
          HAVENEXT: true,
          slugname: "tv-and-entertainment/home-audio",
          subtitle: "",
          description: "",
          descriptionEN: "",
          showcate: true,
          items: [
            {
              node: "010302",
              catname: "ซาวด์บาร์",
              catnameEN: "Sound Bars",
              Lv: 8,
              HAVENEXT: false,
              slugname: "tv-and-entertainment/home-audio/sound-bars",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 1,
            },
            {
              node: "010304",
              catname: "Amplifier",
              catnameEN: "Amplifier",
              Lv: 8,
              HAVENEXT: false,
              slugname: "tv-and-entertainment/home-audio/amplifier",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 3,
            },
            {
              node: "010305",
              catname: "เครื่องดนตรี",
              catnameEN: "Musical instruments",
              Lv: 8,
              HAVENEXT: false,
              slugname: "tv-and-entertainment/home-audio/music-instruments",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 4,
            },
            {
              node: "010303",
              catname: "เครื่องเสียงประเภทอื่นๆ",
              catnameEN: "More…",
              Lv: 8,
              HAVENEXT: false,
              slugname: "tv-and-entertainment/home-audio/more-audio",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 5,
            },
          ],
          seq: 99,
        },
        {
          node: "0105",
          catname: "อุปกรณ์เสริมทีวีและเครื่องเสียง",
          catnameEN: "TV & Audio Accessories",
          Lv: 6,
          HAVENEXT: true,
          slugname: "tv-and-entertainment/tv-audio-accessories",
          subtitle: "",
          description: "",
          descriptionEN: "",
          showcate: true,
          items: [
            {
              node: "010501",
              catname: "Media Box",
              catnameEN: "Media Box",
              Lv: 8,
              HAVENEXT: false,
              slugname: "tv-entertainment/tv-audio-accessories/media-bo",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 1,
            },
            {
              node: "010503",
              catname: "ไมโครโฟน",
              catnameEN: "Microphones",
              Lv: 8,
              HAVENEXT: false,
              slugname: "tv-and-entertainment/tv-audio-accessories/microphones",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 2,
            },
            {
              node: "010504",
              catname: "ขาแขวนทีวี",
              catnameEN: "TV Wall Mounts",
              Lv: 8,
              HAVENEXT: false,
              slugname:
                "tv-and-entertainment/tv-audio-accessories/tv-wall-mounts",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 3,
            },
            {
              node: "010505",
              catname: "อุปกรณ์เสริมสำหรับทีวี",
              catnameEN: "TV accessories",
              Lv: 8,
              HAVENEXT: false,
              slugname: "tv-entertainment/tv-audio-accessories/tv-accessories",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 4,
            },
          ],
          seq: 99,
        },
      ],
      seq: 1,
    },
    {
      node: "02",
      catname: "เครื่องใช้ไฟฟ้าภายในบ้าน",
      catnameEN: "Home Appliances",
      Lv: 4,
      nprod: 1906,
      mapto: "NO      ",
      HAVENEXT: true,
      base64img: null,
      slugname: "home-appliance",
      subtitle: "",
      description: "",
      descriptionEN: "",
      showcate: true,
      items: [
        {
          node: "0201",
          catname: "แอร์",
          catnameEN: "Air Conditioning",
          Lv: 6,
          HAVENEXT: true,
          slugname: "home-appliance/air-conditioning",
          subtitle: "",
          description: "",
          descriptionEN: "",
          showcate: true,
          items: [
            {
              node: "020101",
              catname: "แอร์ติดผนัง",
              catnameEN: "Wall Type",
              Lv: 8,
              HAVENEXT: false,
              slugname: "home-appliance/air-conditioning/wall-type",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 99,
            },
            {
              node: "020102",
              catname: "แอร์ติดฝ้าเพดาน",
              catnameEN: "Floor / Ceiling Type",
              Lv: 8,
              HAVENEXT: false,
              slugname: "home-appliance/air-conditioning/floor-ceiling-type",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 99,
            },
            {
              node: "020103",
              catname: "แอร์เคลื่อนที่",
              catnameEN: "Portable Type",
              Lv: 8,
              HAVENEXT: false,
              slugname:
                "home-appliance/air-conditioning/portable-air-conditioning",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 99,
            },
            {
              node: "020104",
              catname: "อุปกรณ์เสริมแอร์",
              catnameEN: "Accessory Air",
              Lv: 8,
              HAVENEXT: false,
              slugname: "home-appliance/air-conditioning/accessory-air",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 99,
            },
          ],
          seq: 99,
        },
        {
          node: "0202",
          catname: "เครื่องซักผ้า",
          catnameEN: "Washing Machines",
          Lv: 6,
          HAVENEXT: true,
          slugname: "home-appliance/washing-machines",
          subtitle: "",
          description: "",
          descriptionEN: "",
          showcate: true,
          items: [
            {
              node: "020201",
              catname: "เครื่องซักผ้าฝาหน้า",
              catnameEN: "Front Load",
              Lv: 8,
              HAVENEXT: false,
              slugname: "home-appliance/washing-machines/front-load",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 1,
            },
            {
              node: "020202",
              catname: "เครื่องซักผ้าฝาบน",
              catnameEN: "Washer 1 Tub",
              Lv: 8,
              HAVENEXT: false,
              slugname: "home-appliance/washing-machines/top-load-1-tub",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 2,
            },
            {
              node: "020203",
              catname: "เครื่องซักผ้าฝาบน 2 ถัง",
              catnameEN: "Washer 2 Tubs",
              Lv: 8,
              HAVENEXT: false,
              slugname: "home-appliance/washing-machines/top-load-2-tubs",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 3,
            },
            {
              node: "020205",
              catname: "เครื่องอบผ้า",
              catnameEN: "Dryer",
              Lv: 8,
              HAVENEXT: false,
              slugname: "home-appliance/washing-machines/dryers",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 4,
            },
            {
              node: "020204",
              catname: "เครื่องซักและอบผ้า",
              catnameEN: "Washer & Dryer",
              Lv: 8,
              HAVENEXT: false,
              slugname: "home-appliances/washing-machines/washer-dryer",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 5,
            },
            {
              node: "020208",
              catname: "เครื่องซักและอบผ้า ทาวเวอร์",
              catnameEN: "Washer & Dryer Tower",
              Lv: 8,
              HAVENEXT: false,
              slugname: "home-appliances/washing-machines/washer-dryer-tower",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 6,
            },
            {
              node: "020207",
              catname: "น้ำยาซักผ้า และ น้ำยาปรับผ้านุ่ม",
              catnameEN: "Fabric Softerner",
              Lv: 8,
              HAVENEXT: false,
              slugname: "home-appliance/washing-machines/softener",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 7,
            },
            {
              node: "020209",
              catname: "อุปกรณ์เสริมเครื่องซักผ้า",
              catnameEN: "Washer Accessories",
              Lv: 8,
              HAVENEXT: false,
              slugname: "home-appliances/washing-machines/washer-accessories",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 99,
            },
          ],
          seq: 99,
        },
        {
          node: "0203",
          catname: "ตู้เย็น",
          catnameEN: "Refrigerators",
          Lv: 6,
          HAVENEXT: true,
          slugname: "home-appliance/refrigerators",
          subtitle: "",
          description: "",
          descriptionEN: "",
          showcate: true,
          items: [
            {
              node: "020301",
              catname: "ตู้เย็น 1 ประตู",
              catnameEN: "1 Door",
              Lv: 8,
              HAVENEXT: false,
              slugname: "home-appliance/refrigerators/one-door-refrigerators",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 1,
            },
            {
              node: "020302",
              catname: "ตู้เย็น 2 ประตู",
              catnameEN: "2 Doors",
              Lv: 8,
              HAVENEXT: false,
              slugname: "home-appliance/refrigerators/two-door-refrigerators",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 2,
            },
            {
              node: "020303",
              catname: "ตู้เย็นมัลติดอร์",
              catnameEN: "Multi Door",
              Lv: 8,
              HAVENEXT: false,
              slugname: "home-appliance/refrigerators/multi-door-refrigerators",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 3,
            },
            {
              node: "020304",
              catname: "ตู้เย็นไซด์-บาย-ไซด์",
              catnameEN: "Side by Side",
              Lv: 8,
              HAVENEXT: false,
              slugname:
                "home-appliance/refrigerators/side-by-side-refrigerators",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 4,
            },
            {
              node: "020305",
              catname: "ตู้แช่แข็ง",
              catnameEN: "Freezer",
              Lv: 8,
              HAVENEXT: false,
              slugname: "home-appliance/refrigerators/freezers",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 6,
            },
            {
              node: "020306",
              catname: "ตู้แช่ไวน์",
              catnameEN: "Wine Cellar",
              Lv: 8,
              HAVENEXT: false,
              slugname: "home-appliance/refrigerators/wine-cellars",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 7,
            },
            {
              node: "020309",
              catname: "หน้าบานประตูตู้เย็น",
              catnameEN: "Other Refrigerator",
              Lv: 8,
              HAVENEXT: false,
              slugname: "home-appliance/refrigerators/other-refrigerator",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 8,
            },
            {
              node: "020307",
              catname: "ตู้น้ำดื่ม",
              catnameEN: "Water Dispensers",
              Lv: 8,
              HAVENEXT: false,
              slugname: "home-appliance/refrigerators/water-coolers",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 9,
            },
          ],
          seq: 99,
        },
        {
          node: "0204",
          catname: "เครื่องทำน้ำอุ่น",
          catnameEN: "Shower/Water Heaters",
          Lv: 6,
          HAVENEXT: true,
          slugname: "home-appliance/shower-water-heaters",
          subtitle: "",
          description: "",
          descriptionEN: "",
          showcate: true,
          items: [
            {
              node: "020401",
              catname: "เครื่องทำน้ำอุ่น",
              catnameEN: "Shower Heater",
              Lv: 8,
              HAVENEXT: false,
              slugname: "home-appliance/shower-water-heaters/shower",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 99,
            },
            {
              node: "020402",
              catname: "เครื่องทำน้ำร้อน",
              catnameEN: "Water Heater",
              Lv: 8,
              HAVENEXT: false,
              slugname: "home-appliance/shower-water-heaters/water-heater",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 99,
            },
            {
              node: "020403",
              catname: "ตัวกรองอาบน้ำ",
              catnameEN: "Shower filters",
              Lv: 8,
              HAVENEXT: false,
              slugname: "home-appliances/showerwater-heaters/shower-filters",
              subtitle: null,
              description: null,
              descriptionEN: null,
              showcate: true,
              seq: 99,
            },
          ],
          seq: 99,
        },
        {
          node: "0205",
          catname: "เครื่องล้างจาน",
          catnameEN: "Dishwashers",
          Lv: 6,
          HAVENEXT: true,
          slugname: "home-appliance/dishwashers",
          subtitle: "",
          description: "",
          descriptionEN: "",
          showcate: true,
          items: [
            {
              node: "020501",
              catname: "เครื่องล้างจานตั้งพื้น",
              catnameEN: "Freestand",
              Lv: 8,
              HAVENEXT: false,
              slugname: "home-appliance/dishwashers/freestanding-dishwashers",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 99,
            },
          ],
          seq: 99,
        },
        {
          node: "0207",
          catname: "เครื่องครัวแบบ Built-in",
          catnameEN: "Built-in Kitchen Appliances",
          Lv: 6,
          HAVENEXT: true,
          slugname: "home-appliance/build-in-kitchen-appliances",
          subtitle: "",
          description: "",
          descriptionEN: "",
          showcate: true,
          items: [
            {
              node: "020701",
              catname: "เตาฝัง",
              catnameEN: "Hob",
              Lv: 8,
              HAVENEXT: false,
              slugname: "home-appliance/build-in-kitchen-appliances/hob",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 99,
            },
            {
              node: "020702",
              catname: "เครื่องดูดควัน",
              catnameEN: "Hood",
              Lv: 8,
              HAVENEXT: false,
              slugname: "home-appliance/build-in-kitchen-appliances/hood",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 99,
            },
          ],
          seq: 99,
        },
      ],
      seq: 2,
    },
    {
      node: "04",
      catname: "เครื่องใช้ไฟฟ้าขนาดเล็ก",
      catnameEN: "Small Appliances",
      Lv: 4,
      nprod: 2379,
      mapto: "NO      ",
      HAVENEXT: true,
      base64img: null,
      slugname: "small-appliance",
      subtitle: "",
      description: "",
      descriptionEN: "",
      showcate: true,
      items: [
        {
          node: "0401",
          catname: "เครื่องใช้ไฟฟ้าในครัว",
          catnameEN: "Kitchen Appliances",
          Lv: 6,
          HAVENEXT: true,
          slugname: "small-appliance/kitchen-appliances",
          subtitle: "",
          description: "",
          descriptionEN: "",
          showcate: true,
          items: [
            {
              node: "040119",
              catname: "ไมโครเวฟ",
              catnameEN: "Microwave",
              Lv: 8,
              HAVENEXT: false,
              slugname: "small-appliance/kitchen-appliances/microwave-ovens",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 1,
            },
            {
              node: "040124",
              catname: "หม้อหุงข้าว",
              catnameEN: "Rice Cooker",
              Lv: 8,
              HAVENEXT: false,
              slugname: "small-appliance/kitchen-appliances/rice-cookers",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 2,
            },
            {
              node: "040120",
              catname: "กระทะไฟฟ้า และ เตาปิ้งย่าง",
              catnameEN: "Electric Pan",
              Lv: 8,
              HAVENEXT: false,
              slugname: "small-appliance/kitchen-appliances/electric-pans",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 3,
            },
            {
              node: "040118",
              catname: "เตาอบไฟฟ้า",
              catnameEN: "Oven",
              Lv: 8,
              HAVENEXT: false,
              slugname: "small-appliance/kitchen-appliances/electric-ovens",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 4,
            },
            {
              node: "040123",
              catname: "หม้อทอด และ หม้อทอดไร้น้ำมัน",
              catnameEN: "Deep Fryer",
              Lv: 8,
              HAVENEXT: false,
              slugname: "small-appliance/kitchen-appliances/fryers",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 5,
            },
            {
              node: "040122",
              catname: "หม้อไฟฟ้า และ หม้อเอนกประสงค์",
              catnameEN: "Multi Cooker",
              Lv: 8,
              HAVENEXT: false,
              slugname: "small-appliance/kitchen-appliances/multi-cooker",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 6,
            },
            {
              node: "040117",
              catname: "เตาแม่เหล็กไฟฟ้าและเตาแก๊ส",
              catnameEN: "Induction hob and Gas hob",
              Lv: 8,
              HAVENEXT: false,
              slugname: "small-appliances/kitchen-appliances/induction-hob",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 7,
            },
            {
              node: "040114",
              catname: "เครื่องปิ้งขนมปัง และ แซนด์วิช",
              catnameEN: "Toaster / Sandwich Maker",
              Lv: 8,
              HAVENEXT: false,
              slugname: "small-appliance/kitchen-appliances/toaster",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 8,
            },
            {
              node: "040112",
              catname: "เครื่องทำน้ำแข็ง",
              catnameEN: "Ice Maker",
              Lv: 8,
              HAVENEXT: false,
              slugname: "small-appliance/kitchen-appliances/ice-maker",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 9,
            },
            {
              node: "040104",
              catname: "เครื่องชงชาและกาแฟ",
              catnameEN: "Coffee & Tea Makers",
              Lv: 8,
              HAVENEXT: false,
              slugname: "small-appliance/kitchen-appliances/coffee-tea-makers",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 10,
            },
            {
              node: "040113",
              catname: "เครื่องปั่น และ เครื่องสกัด",
              catnameEN: "Food Preparation",
              Lv: 8,
              HAVENEXT: false,
              slugname: "small-appliance/kitchen-appliances/blenders-juicers",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 11,
            },
            {
              node: "040121",
              catname: "กาต้มน้ำ และ กระติกน้ำร้อน",
              catnameEN: "Thermo Pot",
              Lv: 8,
              HAVENEXT: false,
              slugname: "small-appliance/kitchen-appliances/kettles",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 12,
            },
            {
              node: "040102",
              catname: "เครื่องกดน้ำและเครื่องกรองน้ำ",
              catnameEN: "Electric Pump / Water Purifier",
              Lv: 8,
              HAVENEXT: false,
              slugname:
                "small-appliance/kitchen-appliances/water-dispenser-purifiers",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 13,
            },
            {
              node: "040101",
              catname: "เครื่องเตรียมอาหาร",
              catnameEN: "Food Processor",
              Lv: 8,
              HAVENEXT: false,
              slugname:
                "small-appliance/kitchen-appliances/food-processors-mixers",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 14,
            },
            {
              node: "040103",
              catname: "เครื่องครัว และ อุปกรณ์ในครัว",
              catnameEN: "Kitchen Essentials",
              Lv: 8,
              HAVENEXT: false,
              slugname: "small-appliance/kitchen-appliances/cookware-utensils",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 15,
            },
          ],
          seq: 99,
        },
        {
          node: "0402",
          catname: "อุปกรณ์เสริมความงาม",
          catnameEN: "Other Personal Care",
          Lv: 6,
          HAVENEXT: true,
          slugname: "small-appliance/health-beauty",
          subtitle: "",
          description: "",
          descriptionEN: "",
          showcate: true,
          items: [
            {
              node: "040205",
              catname: "ไดร์เป่าผม",
              catnameEN: "Hair dryers",
              Lv: 8,
              HAVENEXT: false,
              slugname: "small-appliance/health-beauty/hair-dryers",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 1,
            },
            {
              node: "040203",
              catname: "เครื่องม้วนผม",
              catnameEN: "Other Personal Care",
              Lv: 8,
              HAVENEXT: false,
              slugname: "small-appliance/health-beauty/hair-curlers",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 2,
            },
            {
              node: "040204",
              catname: "เครื่องหนีบผม",
              catnameEN: "Hair straighteners",
              Lv: 8,
              HAVENEXT: false,
              slugname: "small-appliance/health-beauty/hair-clippers",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 3,
            },
            {
              node: "040201",
              catname: "เครื่องโกนหนวดและกำจัดขน",
              catnameEN: "Shaver and Hair Remover",
              Lv: 8,
              HAVENEXT: false,
              slugname:
                "small-appliance/health-beauty/shavers-and-hair-remover",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 4,
            },
            {
              node: "040207",
              catname: "ผลิตภัณฑ์และอุปกรณ์ความงามอื่น ๆ",
              catnameEN: "Other beauty products and accessories",
              Lv: 8,
              HAVENEXT: false,
              slugname:
                "small-appliance/health-beauty/other-beauty-products-and-accessories",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 5,
            },
          ],
          seq: 99,
        },
        {
          node: "0403",
          catname: "เตารีด",
          catnameEN: "Iron & Garment care",
          Lv: 6,
          HAVENEXT: true,
          slugname: "small-appliance/iron-garment-care",
          subtitle: "",
          description: "",
          descriptionEN: "",
          showcate: true,
          items: [
            {
              node: "040304",
              catname: "เตารีดแห้ง",
              catnameEN: "Dry Iron",
              Lv: 8,
              HAVENEXT: false,
              slugname: "small-appliance/iron-garment-care/dry-iron",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 1,
            },
            {
              node: "040305",
              catname: "เตารีดไอน้ำ",
              catnameEN: "Steam Iron",
              Lv: 8,
              HAVENEXT: false,
              slugname: "small-appliance/iron-garment-care/steam-iron",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 2,
            },
            {
              node: "040303",
              catname: "เตารีดพกพา",
              catnameEN: "Portable Steam Iron",
              Lv: 8,
              HAVENEXT: false,
              slugname: "small-appliance/iron-garment-care/portable-steam-iron",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 3,
            },
            {
              node: "040302",
              catname: "เตารีดถนอมผ้าไอน้ำ",
              catnameEN: "Garment Steamer",
              Lv: 8,
              HAVENEXT: false,
              slugname: "small-appliance/iron-garment-care/garment-steamers",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 4,
            },
            {
              node: "040301",
              catname: "เตารีดแรงดันไอน้ำ / หม้อต้ม",
              catnameEN: "System Iron",
              Lv: 8,
              HAVENEXT: false,
              slugname: "small-appliance/iron-garment-care/system-iron",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 5,
            },
          ],
          seq: 99,
        },
        {
          node: "0405",
          catname: "พัดลม",
          catnameEN: "Electric Fans",
          Lv: 6,
          HAVENEXT: true,
          slugname: "small-appliance/electric-fans",
          subtitle: "",
          description: "",
          descriptionEN: "",
          showcate: true,
          items: [
            {
              node: "040508",
              catname: "พัดลมพกพา",
              catnameEN: "Portable Fan",
              Lv: 8,
              HAVENEXT: false,
              slugname: "small-appliance/electric-fans/portable-fan",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 1,
            },
            {
              node: "040505",
              catname: "พัดลมตั้งพื้น",
              catnameEN: "Floor Fan",
              Lv: 8,
              HAVENEXT: false,
              slugname: "small-appliance/electric-fans/stand-fans",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 2,
            },
            {
              node: "040504",
              catname: "พัดลมตั้งโต๊ะ",
              catnameEN: "Desk Fan",
              Lv: 8,
              HAVENEXT: false,
              slugname: "small-appliance/electric-fans/table-fans",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 3,
            },
            {
              node: "040507",
              catname: "พัดลมทาวเวอร์",
              catnameEN: "Tower Fan",
              Lv: 8,
              HAVENEXT: false,
              slugname: "small-appliance/electric-fans/tower-fan",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 4,
            },
            {
              node: "040502",
              catname: "พัดลมโคจรและเพดาน",
              catnameEN: "Ceiling Fan",
              Lv: 8,
              HAVENEXT: false,
              slugname: "small-appliance/electric-fans/ceiling-fan",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 5,
            },
            {
              node: "040503",
              catname: "พัดลมไอน้ำ / ไอเย็น",
              catnameEN: "Steam Fan",
              Lv: 8,
              HAVENEXT: false,
              slugname: "small-appliance/electric-fans/air-cooling-fans",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 6,
            },
            {
              node: "040506",
              catname: "พัดลมติดผนัง และ เพดาน",
              catnameEN: "Wall Fan",
              Lv: 8,
              HAVENEXT: false,
              slugname: "small-appliance/electric-fans/wall-ceiling-fans",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 7,
            },
          ],
          seq: 99,
        },
        {
          node: "0406",
          catname: "เครื่องฟอกอากาศ",
          catnameEN: "Air Treatment",
          Lv: 6,
          HAVENEXT: true,
          slugname: "small-appliance/air-treatment",
          subtitle: "",
          description: "",
          descriptionEN: "",
          showcate: true,
          items: [
            {
              node: "040601",
              catname: "เครื่องฟอกอากาศพกพา",
              catnameEN: "Portable Air",
              Lv: 8,
              HAVENEXT: false,
              slugname: "small-appliance/air-treatment/portable-air",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 99,
            },
            {
              node: "040602",
              catname: "เครื่องฟอกอากาศภายในบ้าน",
              catnameEN: "Air Purifier",
              Lv: 8,
              HAVENEXT: false,
              slugname: "small-appliance/air-treatment/air-purifier",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 99,
            },
            {
              node: "040604",
              catname: "เครื่องลดความชื้น",
              catnameEN: "Air Dehumidifer",
              Lv: 8,
              HAVENEXT: false,
              slugname: "small-appliance/air-treatment/air-dehumidifer",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 99,
            },
            {
              node: "040605",
              catname: "แผ่นกรองอากาศ / ไส้กรองอากาศ",
              catnameEN: "Air Purifier Filter",
              Lv: 8,
              HAVENEXT: false,
              slugname: "small-appliance/air-treatment/air-purifier-filter",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 99,
            },
          ],
          seq: 99,
        },
        {
          node: "0408",
          catname: "เครื่องดูดฝุ่น",
          catnameEN: "Vacuum",
          Lv: 6,
          HAVENEXT: true,
          slugname: "small-appliance/vacuum-cleaners",
          subtitle: "",
          description: "",
          descriptionEN: "",
          showcate: true,
          items: [
            {
              node: "040801",
              catname: "เครื่องดูดฝุ่นแบบด้ามจับ",
              catnameEN: "Stick Vacuum",
              Lv: 8,
              HAVENEXT: false,
              slugname: "small-appliance/vacuum-cleaners/stick-vacuum-cleaners",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 99,
            },
            {
              node: "040802",
              catname: "เครื่องดูดฝุ่นแบบกล่อง",
              catnameEN: "Canister Vacuum",
              Lv: 8,
              HAVENEXT: false,
              slugname:
                "small-appliance/vacuum-cleaners/cannister-vacuum-cleaners",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 99,
            },
            {
              node: "040804",
              catname: "หุ่นยนต์ดูดฝุ่น",
              catnameEN: "Robot Vacuum",
              Lv: 8,
              HAVENEXT: false,
              slugname:
                "small-appliance/vacuum-cleaners/robotic-vacuum-cleaners",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 99,
            },
            {
              node: "040805",
              catname: "เครื่องดูดฝุ่นและดูดน้ำ",
              catnameEN: "Dry and Wet Cleaner",
              Lv: 8,
              HAVENEXT: false,
              slugname: "small-appliance/vacuum-cleaners/wet-dry",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 99,
            },
            {
              node: "040806",
              catname: "เครื่องดูดไรฝุ่น",
              catnameEN: "Mite Cleaner",
              Lv: 8,
              HAVENEXT: false,
              slugname: "small-appliance/vacuum-cleaners/mite-cleaner",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 99,
            },
          ],
          seq: 99,
        },
      ],
      seq: 3,
    },
    {
      node: "05",
      catname: "มือถือ / แท็บเล็ต",
      catnameEN: "Phone/ Tablet",
      Lv: 4,
      nprod: 2572,
      mapto: "NO      ",
      HAVENEXT: true,
      base64img: null,
      slugname: "phone-and-tablet",
      subtitle: "",
      description: "",
      descriptionEN: "",
      showcate: true,
      items: [
        {
          node: "0502",
          catname: "มือถือแอนดรอยด์",
          catnameEN: "Android Phone",
          Lv: 6,
          HAVENEXT: true,
          slugname: "phone-and-tablet/android-phone",
          subtitle: "",
          description: "",
          descriptionEN: "",
          showcate: true,
          items: [
            {
              node: "050205",
              catname: "Samsung",
              catnameEN: "Samsung",
              Lv: 8,
              HAVENEXT: false,
              slugname: "phone-and-tablet/android-phone/samsung",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 99,
            },
            {
              node: "050206",
              catname: "Oppo",
              catnameEN: "Oppo",
              Lv: 8,
              HAVENEXT: false,
              slugname: "phone-and-tablet/android-phone/oppo",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 99,
            },
            {
              node: "050207",
              catname: "ViVo",
              catnameEN: "ViVo",
              Lv: 8,
              HAVENEXT: false,
              slugname: "phone-and-tablet/android-phone/vivo",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 99,
            },
            {
              node: "050209",
              catname: "มือถือแอนดรอยด์อื่นๆ",
              catnameEN: "Other Android phones",
              Lv: 8,
              HAVENEXT: false,
              slugname: "phone-and-tablet/android-phone/other-android-phones",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 99,
            },
          ],
          seq: 1,
        },
        {
          node: "0501",
          catname: "iPhone",
          catnameEN: "iPhone",
          Lv: 6,
          HAVENEXT: true,
          slugname: "phone-and-tablet/iphone",
          subtitle: "",
          description: "",
          descriptionEN: "",
          showcate: true,
          items: [
            {
              node: "050107",
              catname: "iPhone 16 Series",
              catnameEN: "iPhone 16 Series",
              Lv: 8,
              HAVENEXT: false,
              slugname: "phone-tablet/iphone/iphone-16-series",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 99,
            },
            {
              node: "050108",
              catname: "iPhone 15 Series",
              catnameEN: "iPhone 15 Series",
              Lv: 8,
              HAVENEXT: false,
              slugname: "phone-and-tablet/iphone/iphone-15-series",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 99,
            },
            {
              node: "050109",
              catname: "iPhone 14 Series",
              catnameEN: "iPhone 14 Series",
              Lv: 8,
              HAVENEXT: false,
              slugname: "phone-and-tablet/iphone/iphone-14-series",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 99,
            },
            {
              node: "050110",
              catname: "iPhone รุ่นอื่นๆ",
              catnameEN: "Other iPhone",
              Lv: 8,
              HAVENEXT: false,
              slugname: "phone-and-tablet/iphone/other-iphone",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 99,
            },
          ],
          seq: 2,
        },
        {
          node: "0503",
          catname: "แท็บเล็ต",
          catnameEN: "Tablets",
          Lv: 6,
          HAVENEXT: true,
          slugname: "phone-and-tablet/tablets",
          subtitle: "",
          description: "",
          descriptionEN: "",
          showcate: true,
          items: [
            {
              node: "050307",
              catname: "Galaxy Tab",
              catnameEN: "Galaxy Tab",
              Lv: 8,
              HAVENEXT: false,
              slugname: "phone-and-tablet/tablets/galaxy-tab",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 1,
            },
            {
              node: "050306",
              catname: "Ipad",
              catnameEN: "Ipad",
              Lv: 8,
              HAVENEXT: false,
              slugname: "phone-and-tablet/tablets/ipad",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 2,
            },
            {
              node: "050309",
              catname: "อื่นๆ",
              catnameEN: "More...",
              Lv: 8,
              HAVENEXT: false,
              slugname: "phone-and-tablet/tablets/more-tablets",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 4,
            },
          ],
          seq: 3,
        },
        {
          node: "0504",
          catname: "อุปกรณ์เสริมมือถือและแท็บเล็ต",
          catnameEN: "Accessories",
          Lv: 6,
          HAVENEXT: true,
          slugname: "phone-and-tablet/phone-and-tablet-accessories",
          subtitle: "",
          description: "",
          descriptionEN: "",
          showcate: true,
          items: [
            {
              node: "050401",
              catname: "เคสและฟิล์ม",
              catnameEN: "Cases and films",
              Lv: 8,
              HAVENEXT: false,
              slugname:
                "phone-and-tablet/phone-and-tablet-accessories/cases-and-films",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 1,
            },
            {
              node: "050402",
              catname: "แท่นชาร์จ",
              catnameEN: "Chargers",
              Lv: 8,
              HAVENEXT: false,
              slugname:
                "phone-and-tablet/phone-and-tablet-accessories/chargers",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 2,
            },
            {
              node: "050403",
              catname: "พาวเวอร์แบงค์",
              catnameEN: "Power Banks",
              Lv: 8,
              HAVENEXT: false,
              slugname:
                "phone-and-tablet/phone-and-tablet-accessories/powerbanks",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 3,
            },
            {
              node: "050404",
              catname: "อะแดปเตอร์และสายชาร์จ",
              catnameEN: "Adapters and chargers",
              Lv: 8,
              HAVENEXT: false,
              slugname:
                "phone-and-tablet/phone-and-tablet-accessories/adapters-and-chargers",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 4,
            },
            {
              node: "050406",
              catname: "อุปกรณ์เสริมไอโฟน",
              catnameEN: "Iphone Accessories",
              Lv: 8,
              HAVENEXT: false,
              slugname:
                "phone-and-tablet/phone-and-tablet-accessories/iphone-accessories",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 5,
            },
            {
              node: "050407",
              catname: "อุปกรณ์เสริมมือถืออื่นๆ",
              catnameEN: "Smart Phone Accessories",
              Lv: 8,
              HAVENEXT: false,
              slugname:
                "phone-and-tablet/phone-and-tablet-accessories/other-smartphones-accessories",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 6,
            },
            {
              node: "050405",
              catname: "อุปกรณ์เสริมแท็บเล็ต",
              catnameEN: "Tablet Accessories",
              Lv: 8,
              HAVENEXT: false,
              slugname:
                "phone-and-tablet/phone-and-tablet-accessories/tablet-accessories",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 7,
            },
          ],
          seq: 4,
        },
      ],
      seq: 4,
    },
    {
      node: "06",
      catname: "เกม",
      catnameEN: "Game",
      Lv: 4,
      nprod: 423,
      mapto: "NO      ",
      HAVENEXT: true,
      base64img: null,
      slugname: "game",
      subtitle: "",
      description: "",
      descriptionEN: "",
      showcate: true,
      items: [
        {
          node: "0601",
          catname: "เครื่องเกมคอนโซล",
          catnameEN: "Console",
          Lv: 6,
          HAVENEXT: true,
          slugname: "game/game-console",
          subtitle: "",
          description: "",
          descriptionEN: "",
          showcate: true,
          items: [
            {
              node: "060101",
              catname: "Nintendo Switch",
              catnameEN: "Nintendo Switch",
              Lv: 8,
              HAVENEXT: false,
              slugname: "game/game-console/nintendo-switch",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 99,
            },
            {
              node: "060102",
              catname: "PlayStation",
              catnameEN: "PlayStation",
              Lv: 8,
              HAVENEXT: false,
              slugname: "game/game-console/playstation",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 99,
            },
            {
              node: "060103",
              catname: "เครื่องเกมคอนโซลอื่นๆ",
              catnameEN: "Other game consoles",
              Lv: 8,
              HAVENEXT: false,
              slugname: "game/game-console/other-game-consoles",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 99,
            },
          ],
          seq: 1,
        },
        {
          node: "0603",
          catname: "แผ่นเกม",
          catnameEN: "Software Game",
          Lv: 6,
          HAVENEXT: true,
          slugname: "game/software-game",
          subtitle: "",
          description: "",
          descriptionEN: "",
          showcate: true,
          items: [
            {
              node: "060301",
              catname: "แผ่นเกม Nintendo Switch",
              catnameEN: "Nintendo Switch games",
              Lv: 8,
              HAVENEXT: false,
              slugname: "game/software-game/nintendo-switch-games",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 99,
            },
            {
              node: "060302",
              catname: "แผ่นเกม PlayStation",
              catnameEN: "PlayStation games",
              Lv: 8,
              HAVENEXT: false,
              slugname: "game/software-game/playstation-games",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 99,
            },
            {
              node: "060303",
              catname: "แผ่นเกม Xbox",
              catnameEN: "Xbox games",
              Lv: 8,
              HAVENEXT: false,
              slugname: "game/software-game/xbox-games",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 99,
            },
          ],
          seq: 2,
        },
        {
          node: "0602",
          catname: "เครื่องเกมคอมพิวเตอร์",
          catnameEN: "Gaming Gear",
          Lv: 6,
          HAVENEXT: true,
          slugname: "game/pc-gaming",
          subtitle: "",
          description: "",
          descriptionEN: "",
          showcate: true,
          items: [
            {
              node: "060201",
              catname: "เก้าอี้เกมมิ่ง/โต๊ะเกมมิ่ง",
              catnameEN: "Gaming Furniture",
              Lv: 8,
              HAVENEXT: false,
              slugname: "game/pc-gaming/gaming-furniture",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 99,
            },
            {
              node: "06022 ",
              catname: "ไมโครโฟน",
              catnameEN: null,
              Lv: 8,
              HAVENEXT: false,
              slugname: "",
              subtitle: null,
              description: null,
              descriptionEN: null,
              showcate: true,
              seq: 99,
            },
          ],
          seq: 3,
        },
        {
          node: "0604",
          catname: "อุปกรณ์เสริม",
          catnameEN: "Accessories",
          Lv: 6,
          HAVENEXT: true,
          slugname: "game/accessories",
          subtitle: "",
          description: "",
          descriptionEN: "",
          showcate: true,
          items: [
            {
              node: "060401",
              catname: "เครื่องเล่น VR",
              catnameEN: "Virtual Reality Headsets",
              Lv: 8,
              HAVENEXT: false,
              slugname: "game/accessories/virtual-reality-headsets",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 1,
            },
            {
              node: "060402",
              catname: "คอนโทรลเลอร์",
              catnameEN: "Controllers",
              Lv: 8,
              HAVENEXT: false,
              slugname: "game/accessories/controllers",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 2,
            },
            {
              node: "060403",
              catname: "อุปกรณ์เสริม PlayStation",
              catnameEN: "PlayStation accessories",
              Lv: 8,
              HAVENEXT: false,
              slugname: "game/accessories/playstation-accessories",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 3,
            },
            {
              node: "060203",
              catname: "อุปกรณ์เสริมสำหรับเกม",
              catnameEN: "Gaming Accessories",
              Lv: 8,
              HAVENEXT: false,
              slugname: "game/pc-gaming/gaming-accessories",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 4,
            },
            {
              node: "060404",
              catname: "อุปกรณ์เสริม Nintendo",
              catnameEN: "nintendo accessories",
              Lv: 8,
              HAVENEXT: false,
              slugname: "game/accessories/nintendo-accessories",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 99,
            },
          ],
          seq: 4,
        },
      ],
      seq: 5,
    },
    {
      node: "07",
      catname: "คอมพิวเตอร์ / ออฟฟิศ",
      catnameEN: "Computer/ Office",
      Lv: 4,
      nprod: 2210,
      mapto: "NO      ",
      HAVENEXT: true,
      base64img: null,
      slugname: "computers-and-offices",
      subtitle: "",
      description: "",
      descriptionEN: "",
      showcate: true,
      items: [
        {
          node: "0701",
          catname: "Apple",
          catnameEN: "Apple",
          Lv: 6,
          HAVENEXT: true,
          slugname: "computers-and-offices/apple",
          subtitle: "",
          description: "",
          descriptionEN: "",
          showcate: true,
          items: [
            {
              node: "070103",
              catname: "Macbook",
              catnameEN: "Macbook",
              Lv: 8,
              HAVENEXT: false,
              slugname: "computers-and-offices/apple/macbook",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 1,
            },
            {
              node: "070101",
              catname: "IMac",
              catnameEN: "IMac",
              Lv: 8,
              HAVENEXT: false,
              slugname: "computers-and-offices/apple/imac",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 2,
            },
            {
              node: "070102",
              catname: "Mac & iMac Accessories",
              catnameEN: "Mac & iMac Accessories",
              Lv: 8,
              HAVENEXT: false,
              slugname: "computers-and-offices/apple/mac-imac-accessories",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 3,
            },
          ],
          seq: 99,
        },
        {
          node: "0702",
          catname: "เกมส์มิ่งคอมพิวเตอร์",
          catnameEN: "Gaming Computer",
          Lv: 6,
          HAVENEXT: true,
          slugname: "computers-and-offices/gaming-computer",
          subtitle: "",
          description: "",
          descriptionEN: "",
          showcate: true,
          items: [
            {
              node: "070201",
              catname: "เมาส์",
              catnameEN: "Mice",
              Lv: 8,
              HAVENEXT: false,
              slugname: "computers-and-offices/gaming-computer/mouse",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 99,
            },
            {
              node: "070202",
              catname: "แผ่นรองเมาส์",
              catnameEN: "Mouse pads",
              Lv: 8,
              HAVENEXT: false,
              slugname: "computers-and-offices/gaming-computer/mouse-pads",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 99,
            },
            {
              node: "070203",
              catname: "แล็ปท็อป",
              catnameEN: "Laptops",
              Lv: 8,
              HAVENEXT: false,
              slugname: "computers-and-offices/gaming-computer/laptops",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 99,
            },
            {
              node: "070204",
              catname: "คีย์บอร์ด",
              catnameEN: "Keyboards",
              Lv: 8,
              HAVENEXT: false,
              slugname: "computers-and-offices/gaming-computer/keyboards",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 99,
            },
            {
              node: "070205",
              catname: "จอมอนิเตอร์",
              catnameEN: "Monitors",
              Lv: 8,
              HAVENEXT: false,
              slugname: "computers-and-offices/gaming-computer/monitors",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 99,
            },
            {
              node: "070206",
              catname: "หูฟังเกมมิ่ง",
              catnameEN: "Gaming Headphone",
              Lv: 8,
              HAVENEXT: false,
              slugname:
                "computers-and-offices/gaming-computer/gaming-headphone",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 99,
            },
          ],
          seq: 99,
        },
        {
          node: "0703",
          catname: "แล็ปท๊อป",
          catnameEN: "Laptops",
          Lv: 6,
          HAVENEXT: true,
          slugname: "computers-and-offices/laptops",
          subtitle: "",
          description: "",
          descriptionEN: "",
          showcate: true,
          items: [
            {
              node: "070301",
              catname: "วินโดว์แล็ปท็อป",
              catnameEN: "Windows laptops",
              Lv: 8,
              HAVENEXT: false,
              slugname: "computers-and-offices/laptops/windows-laptops",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 99,
            },
            {
              node: "070303",
              catname: "แล็ปท็อป 2in1",
              catnameEN: "2in1 laptops",
              Lv: 8,
              HAVENEXT: false,
              slugname: "computer-office/laptops/2in1-laptops",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 99,
            },
          ],
          seq: 99,
        },
        {
          node: "0704",
          catname: "คอมพิวเตอร์ตั้งโต๊ะ",
          catnameEN: "Desktops",
          Lv: 6,
          HAVENEXT: true,
          slugname: "computers-and-offices/desktops",
          subtitle: "",
          description: "",
          descriptionEN: "",
          showcate: true,
          items: [
            {
              node: "070401",
              catname: "คอมพิวเตอร์ตั้งโต๊ะ",
              catnameEN: "Windows desktop PC",
              Lv: 8,
              HAVENEXT: false,
              slugname: "computers-and-offices/desktops/windows-desktop-pc",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 99,
            },
          ],
          seq: 99,
        },
        {
          node: "0705",
          catname: "จอมอนิเตอร์และโปรเจคเตอร์",
          catnameEN: "Monitors & Projectors",
          Lv: 6,
          HAVENEXT: true,
          slugname: "computers-and-offices/monitors-and-projectors",
          subtitle: "",
          description: "",
          descriptionEN: "",
          showcate: true,
          items: [
            {
              node: "070501",
              catname: "โปรเจคเตอร์",
              catnameEN: "Projectors",
              Lv: 8,
              HAVENEXT: false,
              slugname:
                "computers-and-offices/monitors-and-projectors/projectors",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 99,
            },
            {
              node: "070502",
              catname: "จอมอนิเตอร์",
              catnameEN: "Monitors",
              Lv: 8,
              HAVENEXT: false,
              slugname:
                "computers-and-offices/monitors-and-projectors/monitors",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 99,
            },
          ],
          seq: 99,
        },
        {
          node: "0706",
          catname: "ปริ้นเตอร์และหมึกพิมพ์",
          catnameEN: "Printers",
          Lv: 6,
          HAVENEXT: true,
          slugname: "computers-and-offices/printers",
          subtitle: "",
          description: "",
          descriptionEN: "",
          showcate: true,
          items: [
            {
              node: "070601",
              catname: "เครื่องพิมพ์มัลติฟังก์ชั่น",
              catnameEN: "All-in-one printers",
              Lv: 8,
              HAVENEXT: false,
              slugname: "computers-and-offices/printers/all-in-one-printers",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 99,
            },
            {
              node: "070603",
              catname: "ปริ้นเตอร์เลเซอร์",
              catnameEN: "Laser printers",
              Lv: 8,
              HAVENEXT: false,
              slugname: "computers-and-offices/printers/laser-printers",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 99,
            },
            {
              node: "070604",
              catname: "ปริ้นเตอร์อิงค์เจ็ท",
              catnameEN: "Inkjet printers",
              Lv: 8,
              HAVENEXT: false,
              slugname: "computers-and-offices/printers/inkjet-printers",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 99,
            },
            {
              node: "070605",
              catname: "หมึกพิมพ์และตลับหมึก",
              catnameEN: "Printer cartridges & toners",
              Lv: 8,
              HAVENEXT: false,
              slugname:
                "computers-and-offices/printers/printer-cartridges-toners",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 99,
            },
          ],
          seq: 99,
        },
        {
          node: "0707",
          catname: "ปากกา & ชุดเครื่องเขียน",
          catnameEN: "Pens & stationery sets",
          Lv: 6,
          HAVENEXT: true,
          slugname: "computers-and-offices/pens-stationery-sets",
          subtitle: "",
          description: "",
          descriptionEN: "",
          showcate: true,
          items: [
            {
              node: "070701",
              catname: "เครื่องคิดเลข",
              catnameEN: "Calculators",
              Lv: 8,
              HAVENEXT: false,
              slugname:
                "computers-and-offices/pens-stationery-sets/calculators",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 99,
            },
            {
              node: "070702",
              catname: "โทรศัพท์และแฟ็กซ์",
              catnameEN: "Phones and fax machines",
              Lv: 8,
              HAVENEXT: false,
              slugname:
                "computers-and-offices/pens-stationery-sets/phones-and-fax-machines",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 99,
            },
            {
              node: "070703",
              catname: "อุปกรณ์สำนักงานอื่น ๆ",
              catnameEN: "Other office supplies",
              Lv: 8,
              HAVENEXT: false,
              slugname:
                "computers-and-offices/pens-stationery-sets/other-office-supplies",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 99,
            },
          ],
          seq: 99,
        },
        {
          node: "0708",
          catname: "อุปกรณ์เชื่อมต่ออินเทอร์เน็ต",
          catnameEN: "Internet & Networking",
          Lv: 6,
          HAVENEXT: true,
          slugname: "computers-and-offices/internet-and-networking",
          subtitle: "",
          description: "",
          descriptionEN: "",
          showcate: true,
          items: [
            {
              node: "070801",
              catname: "ไวร์เลสเร้าเตอร์",
              catnameEN: "Wireless Routers",
              Lv: 8,
              HAVENEXT: false,
              slugname:
                "computers-and-offices/internet-and-networking/wireless-routers",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 99,
            },
            {
              node: "070802",
              catname: "อุปกรณ์เน็ตเวิร์ค",
              catnameEN: "Network equipments",
              Lv: 8,
              HAVENEXT: false,
              slugname:
                "computers-and-offices/internet-and-networking/network-equipments",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 99,
            },
          ],
          seq: 99,
        },
        {
          node: "0709",
          catname: "อุปกรณ์เสริมคอมพิวเตอร์",
          catnameEN: "Computer Accessories",
          Lv: 6,
          HAVENEXT: true,
          slugname: "computers-and-offices/computer-accessories",
          subtitle: "",
          description: "",
          descriptionEN: "",
          showcate: true,
          items: [
            {
              node: "070902",
              catname: "เมาส์",
              catnameEN: "Mice",
              Lv: 8,
              HAVENEXT: false,
              slugname: "computers-and-offices/computer-accessories/mouse ",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 1,
            },
            {
              node: "070906",
              catname: "คีย์บอร์ด",
              catnameEN: "Keyboards",
              Lv: 8,
              HAVENEXT: false,
              slugname: "computers-and-offices/computer-accessories/keyboards",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 2,
            },
            {
              node: "070909",
              catname: "อะแดปเตอร์และเคเบิล",
              catnameEN: "Adapters and cables",
              Lv: 8,
              HAVENEXT: false,
              slugname:
                "computers-and-offices/computer-accessories/adapters-and-cables",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 3,
            },
            {
              node: "070905",
              catname: "กล้องเว็บแคม",
              catnameEN: "Gaming Camera",
              Lv: 8,
              HAVENEXT: false,
              slugname: "computers-and-offices/computer-accessories/webcam",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 4,
            },
            {
              node: "070903",
              catname: "แผ่นรองเมาส์",
              catnameEN: "Mouse pads",
              Lv: 8,
              HAVENEXT: false,
              slugname: "computers-and-offices/computer-accessories/mouse-pads",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 5,
            },
            {
              node: "070907",
              catname: "ซอฟต์แวร์",
              catnameEN: "Software",
              Lv: 8,
              HAVENEXT: false,
              slugname: "computers-and-offices/computer-accessories/software",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 6,
            },
            {
              node: "070901",
              catname: "เครื่องสำรองไฟ",
              catnameEN: "Power banks",
              Lv: 8,
              HAVENEXT: false,
              slugname:
                "computers-and-offices/computer-accessories/power-banks",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 7,
            },
            {
              node: "070912",
              catname: "ชิ้นส่วนประกอบ",
              catnameEN: "Components",
              Lv: 8,
              HAVENEXT: false,
              slugname: "computers-and-offices/computer-accessories/components",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 8,
            },
            {
              node: "070904",
              catname: "กระเป๋า และเคส",
              catnameEN: "Laptop bags & Cases",
              Lv: 8,
              HAVENEXT: false,
              slugname:
                "computers-and-offices/computer-accessories/laptop-bags-and-cases",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 9,
            },
            {
              node: "070911",
              catname: "อุปกรณ์เสริมคอมพิวเตอร์อื่น ๆ",
              catnameEN: "Computer accessories",
              Lv: 8,
              HAVENEXT: false,
              slugname:
                "computers-and-offices/computer-accessories/computer-accessories",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 11,
            },
          ],
          seq: 99,
        },
        {
          node: "0711",
          catname: "ฮาร์ดดิสและจัดเก็บข้อมูล",
          catnameEN: "Harddrives & Storage",
          Lv: 6,
          HAVENEXT: true,
          slugname: "computers-and-offices/harddrives-and-storage",
          subtitle: "",
          description: "",
          descriptionEN: "",
          showcate: true,
          items: [
            {
              node: "071101",
              catname: "เมมโมรี่การ์ดและรีดเดอร์",
              catnameEN: "Memory card & Readers",
              Lv: 8,
              HAVENEXT: false,
              slugname:
                "computers-and-offices/harddrives-and-storage/memory-card-and-readers",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 99,
            },
            {
              node: "071102",
              catname: "แฟลชไดร์ฟ",
              catnameEN: "USB Flash drives",
              Lv: 8,
              HAVENEXT: false,
              slugname:
                "computers-and-offices/harddrives-and-storage/usb-flash-drives",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 99,
            },
            {
              node: "071103",
              catname: "ฮาร์ดดิสพกพา",
              catnameEN: "External Harddrives",
              Lv: 8,
              HAVENEXT: false,
              slugname:
                "computers-and-offices/harddrives-and-storage/external-harddrives",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 99,
            },
          ],
          seq: 99,
        },
      ],
      seq: 6,
    },
    {
      node: "08",
      catname: "แกตเจ็ด & สมาร์ท",
      catnameEN: "Smart Tech & Gadgets",
      Lv: 4,
      nprod: 1764,
      mapto: "NO      ",
      HAVENEXT: true,
      base64img: null,
      slugname: "smart-tech-and-gadgets",
      subtitle: "",
      description: "",
      descriptionEN: "",
      showcate: true,
      items: [
        {
          node: "0803",
          catname: "สมาร์ทโฮม",
          catnameEN: "Smart Home",
          Lv: 6,
          HAVENEXT: true,
          slugname: "smart-tech-and-gadgets/smart-home",
          subtitle: "",
          description: "",
          descriptionEN: "",
          showcate: true,
          items: [
            {
              node: "080301",
              catname: "ไฟอัจฉริยะ",
              catnameEN: "Smart lights",
              Lv: 8,
              HAVENEXT: false,
              slugname: "smart-tech-and-gadgets/smart-home/smart-lights",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 99,
            },
            {
              node: "080303",
              catname: "อุปกรณ์สมาร์ทโฮม",
              catnameEN: "Home Solutions",
              Lv: 8,
              HAVENEXT: false,
              slugname: "smart-tech-and-gadgets/smart-home/home-solutions",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 99,
            },
          ],
          seq: 1,
        },
        {
          node: "0802",
          catname: "ของเล่นอัจฉริยะ & แกดเจ็ต",
          catnameEN: "Smart Toys & Gadgets",
          Lv: 6,
          HAVENEXT: true,
          slugname: "smart-tech-and-gadgets/smart-toys-and-gadgets",
          subtitle: "",
          description: "",
          descriptionEN: "",
          showcate: true,
          items: [
            {
              node: "080202",
              catname: "แทรคเกอร์",
              catnameEN: "Activity tracker",
              Lv: 8,
              HAVENEXT: false,
              slugname:
                "smart-tech-and-gadgets/smart-toys-and-gadgets/activity-tracker",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 1,
            },
            {
              node: "080204",
              catname: "ของเล่นอัจฉริยะ",
              catnameEN: "Smart Toys",
              Lv: 8,
              HAVENEXT: false,
              slugname:
                "smart-tech-and-gadgets/smart-toys-and-gadgets/smart-toys",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 2,
            },
          ],
          seq: 2,
        },
        {
          node: "0804",
          catname: "หูฟัง",
          catnameEN: "Headphone",
          Lv: 6,
          HAVENEXT: true,
          slugname: "smart-tech-and-gadgets/headphone",
          subtitle: "",
          description: "",
          descriptionEN: "",
          showcate: true,
          items: [
            {
              node: "080404",
              catname: "หูฟังบลูทูธ",
              catnameEN: "Bluetooth Headphones",
              Lv: 8,
              HAVENEXT: false,
              slugname: "smart-tech-and-gadgets/headphone/bluetooth-headphones",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 1,
            },
            {
              node: "080402",
              catname: "หูฟังมีสาย",
              catnameEN: "Wired headphone",
              Lv: 8,
              HAVENEXT: false,
              slugname: "smart-tech-and-gadgets/headphone/in-ear-headphone",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 2,
            },
            {
              node: "080403",
              catname: "หูฟังแบบครอบหู",
              catnameEN: "On-ear Headphone",
              Lv: 8,
              HAVENEXT: false,
              slugname: "smart-tech-and-gadgets/headphone/on-ear-headphone",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 3,
            },
            {
              node: "080405",
              catname: "อุปกรณ์เสริมหูฟัง",
              catnameEN: "Headphones accessories",
              Lv: 8,
              HAVENEXT: false,
              slugname:
                "smart-tech-and-gadgets/headphone/headphones-accessories",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 4,
            },
          ],
          seq: 3,
        },
        {
          node: "0805",
          catname: "อุปกรณ์สวมใส่อัจฉริยะ",
          catnameEN: "Wearables",
          Lv: 6,
          HAVENEXT: true,
          slugname: "smart-tech-and-gadgets/wearables",
          subtitle: "",
          description: "",
          descriptionEN: "",
          showcate: true,
          items: [
            {
              node: "080501",
              catname: "Apple watches",
              catnameEN: "Apple watches",
              Lv: 8,
              HAVENEXT: false,
              slugname: "smart-tech-and-gadgets/wearables/apple-watches",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 99,
            },
            {
              node: "080503",
              catname: "สมาร์ทวอทช์",
              catnameEN: "Smart watches",
              Lv: 8,
              HAVENEXT: false,
              slugname: "smart-tech-and-gadgets/wearables/smart-watches",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 99,
            },
            {
              node: "080504",
              catname: "อุปกรณ์เสริม Apple watch",
              catnameEN: "Apple watch accessories",
              Lv: 8,
              HAVENEXT: false,
              slugname:
                "smart-tech-and-gadgets/wearables/apple-watch-accessories",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 99,
            },
            {
              node: "080505",
              catname: "อุปกรณ์เสริม สมาร์ทวอทช์",
              catnameEN: "Smart watch accessories",
              Lv: 8,
              HAVENEXT: false,
              slugname:
                "smart-tech-and-gadgets/wearables/smart-watch-accessories",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 99,
            },
          ],
          seq: 4,
        },
        {
          node: "0801",
          catname: "กล้อง",
          catnameEN: "Camera",
          Lv: 6,
          HAVENEXT: true,
          slugname: "smart-tech-and-gadgets/camera",
          subtitle: "",
          description: "",
          descriptionEN: "",
          showcate: true,
          items: [
            {
              node: "080102",
              catname: "โดรน",
              catnameEN: "Dron",
              Lv: 8,
              HAVENEXT: false,
              slugname: "smart-tech-and-gadgets/camera/drones",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 1,
            },
            {
              node: "080103",
              catname: "กล้องแอคชั่น",
              catnameEN: "Action Cameras",
              Lv: 8,
              HAVENEXT: false,
              slugname: "smart-tech-and-gadgets/camera/action-camera",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 2,
            },
            {
              node: "080105",
              catname: "กล้องติดรถยนต์",
              catnameEN: "Car Camera",
              Lv: 8,
              HAVENEXT: false,
              slugname: "smart-tech-and-gadgets/camera/car-camera",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 3,
            },
            {
              node: "080106",
              catname: "กล้องวงจรปิด",
              catnameEN: "Surveillance Cameras",
              Lv: 8,
              HAVENEXT: false,
              slugname: "smart-tech-and-gadgets/cameracctv-and-ip-cameras",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 4,
            },
            {
              node: "080101",
              catname: "แบตเตอรี่และอุปกรณ์ชาร์จไฟ",
              catnameEN: "Batteries & Chargers",
              Lv: 8,
              HAVENEXT: false,
              slugname: "smart-tech-and-gadgets/camera/batteries-and-chargers",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 6,
            },
            {
              node: "080107",
              catname: "อุปกรณ์เสริมกล้อง",
              catnameEN: "Camera Accessories",
              Lv: 8,
              HAVENEXT: false,
              slugname: "smart-tech-and-gadgets/camera/camera-accessories",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 7,
            },
            {
              node: "080108",
              catname: "อุปกรณ์เสริมกล้องแอคชั่น",
              catnameEN: "Action camera accessories",
              Lv: 8,
              HAVENEXT: false,
              slugname:
                "smart-tech-and-gadgets/camera/action-camera-accessories",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 8,
            },
          ],
          seq: 5,
        },
      ],
      seq: 7,
    },
    {
      node: "03",
      catname: "ของแต่งบ้าน และ อุปกรณ์",
      catnameEN: "Home & Life Style",
      Lv: 4,
      nprod: 442,
      mapto: "NO      ",
      HAVENEXT: true,
      base64img: null,
      slugname: "home-life-style",
      subtitle: "",
      description: "",
      descriptionEN: "",
      showcate: true,
      items: [
        {
          node: "0301",
          catname: "เฟอร์นิเจอร์ และ ของแต่งบ้าน",
          catnameEN: "Home Furniture & Decoration",
          Lv: 6,
          HAVENEXT: true,
          slugname: "home-life-style/home-furniture-decoration",
          subtitle: "",
          description: "",
          descriptionEN: "",
          showcate: true,
          items: [
            {
              node: "030101",
              catname: "โคมไฟ",
              catnameEN: "Lamps",
              Lv: 8,
              HAVENEXT: false,
              slugname:
                "home-life-style/home-furniture-decoration/decorative-lamps",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 99,
            },
            {
              node: "030102",
              catname: "นาฬิกา",
              catnameEN: "Clocks",
              Lv: 8,
              HAVENEXT: false,
              slugname: "home-life-style/home-furniture-decoration/clocks",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 99,
            },
          ],
          seq: 1,
        },
        {
          node: "0303",
          catname: "ห้องครัว และ อุปกรณ์ประกอบอาหาร",
          catnameEN: "Kitchen & Dining",
          Lv: 6,
          HAVENEXT: true,
          slugname: "home-life-style/kitchen-dining",
          subtitle: "",
          description: "",
          descriptionEN: "",
          showcate: true,
          items: [
            {
              node: "030302",
              catname: "อุปกรณ์ทำความสะอาด",
              catnameEN: "Cleaning Equipment",
              Lv: 8,
              HAVENEXT: false,
              slugname: "home-life-style/kitchen-dining/cleaning-equipment",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 99,
            },
          ],
          seq: 3,
        },
        {
          node: "0304",
          catname: "เครื่องมือ และ อุปกรณ์",
          catnameEN: "Tools & Home Equipment",
          Lv: 6,
          HAVENEXT: true,
          slugname: "home-life-style/tools-home-equipment",
          subtitle: "",
          description: "",
          descriptionEN: "",
          showcate: true,
          items: [
            {
              node: "030406",
              catname: "จักรเย็บผ้า",
              catnameEN: "Sewing Machines",
              Lv: 8,
              HAVENEXT: false,
              slugname: "home-life-style/tools-home-equipment/sewing-machines",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 2,
            },
            {
              node: "030405",
              catname: "อุปกรณ์กำจัดแมลง",
              catnameEN: "Electric Insect Killers",
              Lv: 8,
              HAVENEXT: false,
              slugname:
                "home-life-style/tools-home-equipment/electric-insect-killers",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 3,
            },
            {
              node: "030407",
              catname: "สายไฟ ปลั๊ก และ อแดปเตอร์",
              catnameEN: "Cables Plugs Adaptors",
              Lv: 8,
              HAVENEXT: false,
              slugname:
                "home-life-style/tools-home-equipment/cables-plugs-adaptors",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 4,
            },
            {
              node: "030401",
              catname: "อุปกรณ์ภายในบ้านและอื่นๆ",
              catnameEN: "Home Equipments",
              Lv: 8,
              HAVENEXT: false,
              slugname: "home-life-style/tools-home-equipment/home-equipments",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 6,
            },
          ],
          seq: 4,
        },
        {
          node: "0306",
          catname: "อุปกรณ์ภายนอก และ ตกแต่งสวน",
          catnameEN: "Outdoor & Garden",
          Lv: 6,
          HAVENEXT: false,
          slugname: "home-life-style/outdoor-garden",
          subtitle: "",
          description: "",
          descriptionEN: "",
          showcate: true,
          seq: 6,
        },
        {
          node: "0307",
          catname: "อุปกรณ์สำหรับรถยนต์",
          catnameEN: "Car Accessories",
          Lv: 6,
          HAVENEXT: true,
          slugname: "home-life-style/car-accessories",
          subtitle: "",
          description: "",
          descriptionEN: "",
          showcate: true,
          items: [
            {
              node: "030701",
              catname: "อุปกรณ์เสริมสำหรับรถยนต์",
              catnameEN: "Car Accessories",
              Lv: 8,
              HAVENEXT: false,
              slugname: "home-life-style/car-accessories/car-accessories",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 99,
            },
          ],
          seq: 7,
        },
        {
          node: "0308",
          catname: "สัตว์เลี้ยง",
          catnameEN: "Pet",
          Lv: 6,
          HAVENEXT: true,
          slugname: "home-life-style/pet",
          subtitle: "",
          description: "",
          descriptionEN: "",
          showcate: true,
          items: [
            {
              node: "030801",
              catname: "อุปกรณ์สำหรับสัตว์เลี้ยง",
              catnameEN: "Pet Accessories",
              Lv: 8,
              HAVENEXT: false,
              slugname: "home-life-style/pet/pet-accessories",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 99,
            },
          ],
          seq: 8,
        },
        {
          node: "0309",
          catname: "แฟชั่น",
          catnameEN: "Fashions",
          Lv: 6,
          HAVENEXT: true,
          slugname: "home-life-style/fashions",
          subtitle: "",
          description: "",
          descriptionEN: "",
          showcate: true,
          items: [
            {
              node: "030901",
              catname: "กระเป๋า",
              catnameEN: "Bags",
              Lv: 8,
              HAVENEXT: false,
              slugname: "home-life-style/fashions/bags",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 99,
            },
          ],
          seq: 9,
        },
        {
          node: "0407",
          catname: "อุปกรณ์เพื่อสุขภาพ",
          catnameEN: "Health Care",
          Lv: 6,
          HAVENEXT: true,
          slugname: "small-appliance/health-care",
          subtitle: "",
          description: "",
          descriptionEN: "",
          showcate: true,
          items: [
            {
              node: "040701",
              catname: "เครื่องชั่งน้ำหนัก",
              catnameEN: "Weight Scales",
              Lv: 8,
              HAVENEXT: false,
              slugname: "small-appliance/health-care/weight-scales",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 99,
            },
            {
              node: "040702",
              catname: "เครื่องนวดไฟฟ้า",
              catnameEN: "Electric massagers",
              Lv: 8,
              HAVENEXT: false,
              slugname: "small-appliance/health-care/electric-massagers",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 99,
            },
            {
              node: "040703",
              catname: "แปรงสีฟันไฟฟ้า",
              catnameEN: "Electric Tooth Brush",
              Lv: 8,
              HAVENEXT: false,
              slugname: "small-appliance/health-care/oral-care",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 99,
            },
            {
              node: "040705",
              catname: "หน้ากากอนามัย",
              catnameEN: "Face masks",
              Lv: 8,
              HAVENEXT: false,
              slugname: "small-appliance/health-care/face-mask",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 99,
            },
            {
              node: "040706",
              catname: "อุปกรณ์ตรวจสุขภาพ",
              catnameEN: "Healthcare devices",
              Lv: 8,
              HAVENEXT: false,
              slugname: "small-appliances/health-care/healthcare-devices",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 99,
            },
            {
              node: "040707",
              catname: "อุปกรณ์สุขภาพอื่น ๆ",
              catnameEN: "Other healthcare devices",
              Lv: 8,
              HAVENEXT: false,
              slugname: "small-appliances/health-care/other-healthcare-devices",
              subtitle: "",
              description: "",
              descriptionEN: "",
              showcate: true,
              seq: 99,
            },
          ],
          seq: 11,
        },
      ],
      seq: 9,
    },
  ]);
}
